# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20160726_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(default=datetime.datetime(2016, 7, 26, 20, 44, 55, 996537, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default=2, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
