# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20160728_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
