# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20160728_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
