# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='birthday',
        ),
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 28, 15, 27, 18, 77638, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
