# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_auto_20160728_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='slug',
            new_name='page_slug',
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
