# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_auto_20160808_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_slug',
            field=models.SlugField(blank=True),
        ),
    ]
