# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_auto_20160808_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='views',
        ),
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
