# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_auto_20160810_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('person', 'title')]),
        ),
    ]
