# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_auto_20160819_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_slug',
            new_name='pageid',
        ),
    ]
