# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_auto_20160822_1731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([]),
        ),
    ]
