# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_auto_20160822_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pageid',
            field=models.SlugField(blank=True),
        ),
    ]
