# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_auto_20160822_1809'),
        ('directory', '0019_auto_20160821_2222'),
    ]

    operations = [
    ]
