# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0026_auto_20160902_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryid',
            field=models.SlugField(blank=True),
        ),
    ]
