# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0027_category_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryid',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
