# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0028_auto_20160907_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryid',
            field=models.SlugField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
