# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0031_auto_20160908_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
