# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0032_auto_20160908_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='FB_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='classification',
            field=models.CharField(choices=[('F', 'Friend'), ('C', 'Colleague'), ('L', 'Client')], default=datetime.datetime(2016, 10, 29, 21, 53, 51, 45614, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='dad_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='mum_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='partner_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sibling_names',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([]),
        ),
    ]
