# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0032_auto_20160908_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='classification',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=datetime.datetime(2016, 10, 16, 19, 6, 43, 148003, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([]),
        ),
    ]
