# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0033_auto_20161016_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='classification',
            field=models.CharField(choices=[('F', 'Friend'), ('C', 'Colleague'), ('L', 'Client')], max_length=1),
        ),
    ]
