# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0034_auto_20161016_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
