# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0036_person_fb_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='dad_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='mum_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='partner_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='sibling_names',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='User',
            name='auth_permission',
            field=models.CharField(max_length=100))
    ]
